apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vn32m6ucd-dotnet-basic 
  janus-idp.io/tekton: vn32m6ucd-dotnet-basic
  backstage.io/kubernetes-id: vn32m6ucd-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vn32m6ucd-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  